# Generated by Django 5.1.7 on 2025-03-30 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('char_class', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('deity', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='character_images/')),
                ('skills', models.TextField(blank=True, null=True)),
                ('powers', models.TextField(blank=True, null=True)),
                ('inventory', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
