# Generated by Django 3.1 on 2025-03-18 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='character',
            name='level',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.AddField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
    ]
