# Generated by Django 5.1.7 on 2025-03-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='last_name_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
