# Generated by Django 3.1 on 2025-03-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoArton', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
