# Generated by Django 3.1 on 2025-03-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoArton', '0003_auto_20250314_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
