# Generated by Django 3.0 on 2025-03-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoArton', '0007_auto_20250317_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquimico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espacos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('tipo', models.IntegerField(choices=[(1, 'Catalisadores'), (2, 'Preparados'), (3, 'Venenos')], default=1)),
            ],
        ),
    ]
