# Generated by Django 3.0 on 2025-03-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoArton', '0008_alquimico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poderes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('tipo', models.IntegerField(choices=[(1, 'Tormenta'), (2, 'D&D')], default=1)),
            ],
        ),
    ]
