# Generated by Django 3.0.4 on 2025-03-30 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('combate', 'Combate'), ('destino', 'Destino'), ('magia', 'Magia'), ('concedido', 'Concedido'), ('tormenta', 'Tormenta')], max_length=20)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poderes', models.ManyToManyField(to='users.Poder')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser')),
            ],
        ),
    ]
