# Generated by Django 5.1.7 on 2025-03-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
        ('users', '0002_personagem_poder'),
    ]

    operations = [
    ]
