# Generated by Django 3.0.4 on 2025-03-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem', models.CharField(choices=[('T20', 'Tormenta 20'), ('Ghanor', 'Ghanor'), ('Ameacas', 'Ameaças de Arton')], default='T20', max_length=20)),
                ('tipo', models.CharField(choices=[('menor', 'Menor'), ('medio', 'Médio'), ('maior', 'Maior')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alquimico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem', models.CharField(choices=[('T20', 'Tormenta 20'), ('Ghanor', 'Ghanor'), ('Ameacas', 'Ameaças de Arton')], default='T20', max_length=20)),
                ('tipo', models.CharField(choices=[('preparado', 'Preparado'), ('catalisador', 'Catalisador'), ('veneno', 'Veneno')], max_length=20)),
                ('nivel', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem', models.CharField(choices=[('T20', 'Tormenta 20'), ('Ghanor', 'Ghanor'), ('Ameacas', 'Ameaças de Arton')], default='T20', max_length=20)),
                ('classe', models.CharField(choices=[('simples', 'Simples'), ('marcial', 'Marcial'), ('exotica', 'Exótica')], max_length=10)),
                ('tipo', models.CharField(choices=[('perfuracao', 'Perfuração'), ('corte', 'Corte'), ('impacto', 'Impacto')], max_length=10)),
                ('empunhadura', models.CharField(choices=[('uma-mao', 'Uma mão'), ('duas-maos', 'Duas mãos'), ('leve', 'Leve')], max_length=10)),
                ('dano', models.CharField(max_length=20)),
                ('critico', models.CharField(max_length=10)),
                ('alcance', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Armadilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem', models.CharField(choices=[('T20', 'Tormenta 20'), ('Ghanor', 'Ghanor'), ('Ameacas', 'Ameaças de Arton')], default='T20', max_length=20)),
                ('nivel', models.IntegerField()),
                ('efeito', models.TextField()),
                ('magica', models.BooleanField(default=False)),
                ('cd_resistencia', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Armadura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem', models.CharField(choices=[('T20', 'Tormenta 20'), ('Ghanor', 'Ghanor'), ('Ameacas', 'Ameaças de Arton')], default='T20', max_length=20)),
                ('classe', models.CharField(choices=[('leve', 'Leve'), ('pesada', 'Pesada'), ('escudo', 'Escudo')], max_length=10)),
                ('bonus_defesa', models.IntegerField()),
                ('penalidade', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('efeitos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem', models.CharField(choices=[('T20', 'Tormenta 20'), ('Ghanor', 'Ghanor'), ('Ameacas', 'Ameaças de Arton')], default='T20', max_length=20)),
                ('sintomas', models.TextField()),
                ('tratamento', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Esoterico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem', models.CharField(choices=[('T20', 'Tormenta 20'), ('Ghanor', 'Ghanor'), ('Ameacas', 'Ameaças de Arton')], default='T20', max_length=20)),
                ('tipo', models.CharField(choices=[('encantamento', 'Encantamento'), ('pocao', 'Poção'), ('material', 'Material Especial')], max_length=20)),
                ('nivel', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem', models.CharField(choices=[('T20', 'Tormenta 20'), ('Ghanor', 'Ghanor'), ('Ameacas', 'Ameaças de Arton')], default='T20', max_length=20)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('classe', models.CharField(choices=[('arcana', 'Arcana'), ('divina', 'Divina'), ('universal', 'Universal')], max_length=10)),
                ('escola', models.CharField(choices=[('abjuracao', 'Abjuração'), ('adivinhacao', 'Adivinhação'), ('convocacao', 'Convocação'), ('encantamento', 'Encantamento'), ('evocacao', 'Evocação'), ('ilusao', 'Ilusão'), ('necromancia', 'Necromancia'), ('transmutacao', 'Transmutação')], max_length=20)),
                ('ciclo', models.IntegerField()),
                ('acao', models.CharField(max_length=50)),
                ('alcance', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=50)),
                ('alvo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('modificador', models.CharField(max_length=50)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Melhoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('arma', 'Arma'), ('armadura', 'Armadura'), ('escudo', 'Escudo'), ('esoterico', 'Esotérico'), ('ferramenta', 'Ferramenta'), ('vestuario', 'Vestuário'), ('qualquer', 'Qualquer')], max_length=20)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('combate', 'Combate'), ('destino', 'Destino'), ('magia', 'Magia')], max_length=20)),
                ('requisitos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem', models.CharField(choices=[('T20', 'Tormenta 20'), ('Ghanor', 'Ghanor'), ('Ameacas', 'Ameaças de Arton')], default='T20', max_length=20)),
                ('tipo', models.CharField(choices=[('terrestre', 'Terrestre'), ('aquatico', 'Aquático'), ('aereo', 'Aéreo')], max_length=20)),
                ('capacidade', models.IntegerField()),
                ('velocidade', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
