# Generated by Django 5.1.7 on 2025-03-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t20', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatisticacriaturasolo',
            options={'ordering': ['nd'], 'verbose_name': 'Estatística de Criatura Especial', 'verbose_name_plural': 'Estatísticas de Criaturas Especiais'},
        ),
    ]
