# Generated by Django 3.0.4 on 2025-03-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t20', '0002_auto_20250327_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorio',
            name='tipo',
            field=models.CharField(choices=[('menor', 'Menor'), ('medio', 'Médio'), ('maior', 'Maior')], max_length=20),
        ),
        migrations.AlterField(
            model_name='arma',
            name='classe',
            field=models.CharField(choices=[('simples', 'Simples'), ('marcial', 'Marcial'), ('exotica', 'Exótica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='arma',
            name='critico',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='arma',
            name='empunhadura',
            field=models.CharField(choices=[('uma-mao', 'Uma mão'), ('duas-maos', 'Duas mãos'), ('leve', 'Leve')], max_length=20),
        ),
        migrations.AlterField(
            model_name='arma',
            name='tipo',
            field=models.CharField(choices=[('perfuracao', 'Perfuração'), ('corte', 'Corte'), ('impacto', 'Impacto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='armadura',
            name='bonus_defesa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armadura',
            name='classe',
            field=models.CharField(choices=[('leve', 'Leve'), ('pesada', 'Pesada'), ('escudo', 'Escudo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='magia',
            name='classe',
            field=models.CharField(choices=[('arcana', 'Arcana'), ('divina', 'Divina'), ('universal', 'Universal')], max_length=20),
        ),
    ]
