# Generated by Django 5.1.7 on 2025-03-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t20', '0003_alter_recompensasarmaduras_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecompensasArmasSuperiores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_percent', models.CharField(db_column='d%', max_length=10)),
                ('melhoria', models.TextField()),
            ],
            options={
                'verbose_name': 'Recompensa de Arma Superior',
                'verbose_name_plural': 'Recompensas de Armas Superiores',
                'db_table': 'recompensas_armas_superiores',
            },
        ),
        migrations.CreateModel(
            name='RecompensasEsotericosSuperiores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_percent', models.CharField(db_column='d%', max_length=10)),
                ('melhoria', models.TextField()),
            ],
            options={
                'verbose_name': 'Recompensa de Esotérico Superior',
                'verbose_name_plural': 'Recompensas de Esotéricos Superiores',
                'db_table': 'recompensas_esotericos_superiores',
            },
        ),
        migrations.AlterField(
            model_name='magia',
            name='duracao',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='magia',
            name='resistencia',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
