# Generated by Django 5.1.7 on 2025-03-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t20', '0004_recompensasarmassuperiores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
