# Generated by Django 5.1.7 on 2025-03-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t20', '0007_alter_recompensasarmassuperiores_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aparencia',
        ),
        migrations.AlterModelOptions(
            name='recompensasarmassuperiores',
            options={'ordering': ['d_percent'], 'verbose_name': 'Recompensa de Arma Superior', 'verbose_name_plural': 'Recompensas de Armas Superiores'},
        ),
        migrations.AddField(
            model_name='poder',
            name='aprimoramentos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='poder',
            name='requisito_outros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='poder',
            name='requisito_pericias',
        ),
        migrations.RemoveField(
            model_name='poder',
            name='requisito_poderes',
        ),
        migrations.AlterField(
            model_name='poder',
            name='tipo',
            field=models.CharField(choices=[('combate', 'Combate'), ('destino', 'Destino'), ('magia', 'Magia'), ('concedido', 'Concedido'), ('tormenta', 'Tormenta'), ('racial', 'Racial')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='recompensasarmassuperiores',
            table='recompensas_armas_superiores',
        ),
        migrations.AddField(
            model_name='poder',
            name='requisito_pericias',
            field=models.ManyToManyField(blank=True, related_name='poderes_requeridos', to='t20.pericia'),
        ),
        migrations.AddField(
            model_name='poder',
            name='requisito_poderes',
            field=models.ManyToManyField(blank=True, related_name='requerido_por', to='t20.poder'),
        ),
    ]
