# Generated by Django 5.1.7 on 2025-03-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t20', '0009_aparencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.CharField(choices=[('T20', 'Tormenta 20'), ('Ghanor', 'Ghanor'), ('Ameacas', 'Ameaças de Arton'), ('Deuses', 'Deuses e Heróis')], default='Deuses', max_length=20)),
                ('alinhamento', models.CharField(blank=True, choices=[('Bom', 'Bom'), ('Neutro', 'Neutro'), ('Maligno', 'Maligno'), ('Caótico', 'Caótico'), ('Legal', 'Legal'), ('Neutro Bom', 'Neutro Bom'), ('Neutro Maligno', 'Neutro Maligno'), ('Qualquer', 'Qualquer')], max_length=20, null=True)),
                ('devotacao_descricao', models.TextField(blank=True, null=True)),
                ('obrigacoes', models.JSONField(blank=True, default=list)),
                ('referencia_fonte', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_pagina', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Deus',
                'verbose_name_plural': 'Deuses',
                'ordering': ['title'],
            },
        ),
    ]
